services:
  - type: web
    name: bitespeed-identity
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://bitespeed_owner:npg_tyk04jLgSKzC@ep-polished-boat-a1hv9qtw-pooler.ap-southeast-1.aws.neon.tech/bitespeed?sslmode=require
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
